#!/usr/bin/env node

const fs = require("fs");

// Internal usage: bin2doc.js $script … ; Converts a script usage to a proper jsdoc.

input2log = function(input) {
  input = input.replace(new RegExp("\\\\`", "gs"), "`").replace(new RegExp("\\s+$", "gs"), "");
  let name  = input.replace(new RegExp("^Usage\\s*:\\s*([^\\s]*).*", "gs"), "$1");
  let usage = input.replace(new RegExp("\n.*", "gs"), "");
  let body = input.replace(new RegExp("^[^\n]*\n", "gs"), "").replace(new RegExp("\n","gs"), "\n * ");
  console.log(`
/**
 * @function ${name}
 * @memberof scripts
 * @static
 * \`\`\`
 * ${usage}
 * \`\`\`
 * @description ${body}
 */`);
}

process.argv.slice(2).forEach(file => {
  let input = fs.readFileSync(file, "utf-8");
  if(input.match(new RegExp("^#!/bin/bash.*", "gs"))) {
    input2log(input.replace(new RegExp(".*<<\\s*EOU\\s*(Usage\\s*:.*)EOU.*", "gs"), "$1").replace(new RegExp("\\\\\\$", "gs"), "$"));
  } else if(input.match(new RegExp("^#![^\n]*node.*", "gs"))) {
    input2log(input.replace(new RegExp(".*console\\.log\\(`\\s*(Usage\\s*:(\\`|[^`])*)`.*", "gs"), "$1"));
  } else {
    console.log(`
/**
 * @function ${file}
 * @memberof scripts
*/`);
  }
});

			     


	
