#!/bin/bash

confirm() { # Usage: confirm $message [$exit_message] ; Asks a true/false question ; returns the boolean answer ; exits if false, with $exit=y.
    read -p "$1? (y/N) : " -n 1 -e rep ; if [ "$rep" = "y" ] ; then true ; else if [ \! -z "$exit_message" ] ; then echo "$exit_message" ; exit ; fi ; false ; fi
}
needfor() { # Usage: needfor package ; Tests if a package is installed before used, and proposes to install otherwise.
  if ! dpkg-query -Wf'${db:Status}' "$1" 2>/dev/null ; then
    if confirm "The '$1' package is not installed ? Shall we" "It cannot be proceeded, bye." ; then sudo apt install "$1" ; fi
  fi
}
if [ -z "$BROWSER" ]
then
 for b in chromium firefox google-chrome brave opera
 do if which -s b ; then export BROWSER=$b ; break fi
 done
fi	

backup() { # Usage: backup file [-v|--verbose] ; Backups a file if it exists, appending a '~' suffix.
  if [ -f "$1" ] ; then
    if [ \! -z "$2" ] ; then echo "The file '$1' exists and is renamed appendig a '~' suffix." ; fi
    backup "$1~"
    mv "$1" "$1~"
  fi
}

confirm "This script will setup an idnai-* driven package, is it OK" true

needfor nodejs

if confirm "Are you in your scketchbook directory"
then
  read -p "What is, please, the your GitHub login: " -e login
  read -p "What is, please, the package name: " -e name
  ok="`nodejs -e 'fetch(\"https://github.com/$login/$name\").then((response) => { if (response.ok) console.log("ok") });'`"
  if [ -z "$ok:" ] ; then cat <<EOF
Sorry https://github.com/$login/$name does not exist:
 - The package repository has to be created on GitHub first.
 - You login '$login' or the package name '$name' may be wrong.
Please check and rerun. Bye.
EOF
    $BROWSER "https://vthierry.dithub.io/idnai-make/setup-1.pdf"
    exit
  fi
  backup "$name" -v
  echo "[1/4] Cloning your repository, using ssh …"
  git clone git@github.com:$login/$name.git
  echo "[2/4] Installing a few useful files …"
  cd $name
  nodejs -e 'fetch("https://vthierry.github.io/idnai-make/setup.zip");'
  unzip -o setup.zip ; rm setup.zip
  sed "s/@login/$login/" < makefile~ > makefile
  bin/update
  echo "[3/4] Updating the GitHub repository"
  git add makefile bin/* docs/*
  git commit -a -m "setup as an idnai-* driven package"
  git push origin master --force
  echo "[4/4] Next step is for you, to activate the documentation pages …"
  $BROWSER "https://vthierry.dithub.io/idnai-make/setup-3.pdf"
  $BROWSER "https://github.com/$login/$name/settings/pages"
else cat <<EOF
In that case:
- Choose and/or create ``scketchbook directory´´, for instance, '~/scketchbook/'.
- Better move this `setup` script in it.
- Rerun this script.
EOF
fi

  
